kind: Namespace
apiVersion: v1
metadata:
  name: kube-logging


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data1
  namespace: kube-logging
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data2
  namespace: kube-logging
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
